import sys
import os
import re
import traceback
from datetime import datetime
from PyQt5.QtWidgets import (QApplication, QWidget, QVBoxLayout, QHBoxLayout, 
                             QLineEdit, QPushButton, QLabel, QCheckBox, 
                             QFileDialog, QCompleter, QComboBox, QMessageBox, 
                             QMainWindow)
from PyQt5.QtCore import Qt, QSortFilterProxyModel, QStringListModel
from PyQt5.QtGui import QIcon

STYLE_PREFIX = "{\\t(0,300,\\fscx100\\fscy100\\c&HFFFFFF&\\3c&H5D0F83&\\blur0\\bord0)\\an2\\t(0,500,\\1c&HE3A8FF&\\3c&H5D0F83&\\blur0\\bord1.5)\\t(0,300,\\fscx100\\fscy100)\\fad(300,300)\\shad2\\blur1\\fad(300,0)}"
IMPORTANT_ACTORS = ["Chizuko", "Chrome", "Voleur", "Berry", "Noichigo", "Mashirou", "Grandpa", "Ako", "Mère", "Serveuse", "Professeur", "Kurokawa", "Takuya", "Rika"]
NON_DIALOG_ACTORS = ["title", "SFX", "SFX Sign", "Sfx sign", "Eptitle Sign", "Eyecatch Sign"]
NON_DIALOG_STYLE = "Default"
NON_IMPORTANT_ACTOR_STYLE = "main"
EXCEPTION_CASE = {}
AVS_ANIME_NAME_TEMPLATE = """Dialogue: 0,0:00:00.00,0:00:05.00,AVS_Intro,,0,0,0,,{\\c&H0000FF&\\3c&HFFFFFF&\\fs60\\bord6\\fnHeroes Legend}AnimeVietsub\\N{\\3c&H000000&\\bord3\\c&HFFFFFF&\\fnUVN Van}Hân hạnh giới thiệu Anime\\N(Tên Anime - Tập)"""
AVS_CONTENT_TEMPLATE = """
[Script Info]
; Script generated by Aegisub 9663-feature-8fb8e9000
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:24000/1001:40000:1920:1080:47:163:254:
Video AR Value: 1.777778
Video Zoom Percent: 0.500000
Active Line: 5

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,UVN Van,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,40,1
Style: AVS_Notify,UTM Avo,55,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,95,95,0,0,1,4,0,8,23,23,30,1
Style: AVS_Logo,Heroes Legend,45,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,7,23,23,23,1
Style: AVS_Hot,UTM Avo,60,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,8,10,10,30,1
Style: AVS_Notify_1,UTM Avo,20,&HC9FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,9,23,23,23,1
Style: AVS_Notify_2,UTM Avo,25,&H59FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,9,23,23,23,1
Style: Default,Arial,50,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,10,10,0,1
Style: AVS_Notify,UTM Avo,55,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,95,95,0,0,1,4,0,8,23,23,30,1
Style: AVS_Logo,Heroes Legend,45,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,7,23,23,23,1
Style: AVS_Hot,UTM Avo,60,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,8,10,10,30,1
Style: AVS_Notify_1,UTM Avo,20,&HC9FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,9,23,23,23,1
Style: AVS_Notify_2,UTM Avo,25,&H59FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,9,23,23,23,1
Style: DefaultTop,UVN Van,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,8,10,10,40,1
Style: AVS_Notify_3,UVN Tin Tuc Hep,50,&HCDFFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,1.3,0,1,0,0,2,23,23,50,1
Style: AVS_Intro,UVN Van,60,&H00FFFFFF,&H000000FF,&H000000FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,5,10,10,40,1
Style: main,UVN Van,80,&H00FFFFFF,&H000000FF,&H00564130,&H8DFFC900,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Ako,UVN Van,80,&H00FFFFFF,&H000000FF,&H0020335B,&H8D3D5F94,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Chizuko,UVN Van,80,&H00FFFFFF,&H000000FF,&H004B2F33,&H82FF97AC,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Chrome,UVN Van,80,&H00FFFFFF,&H000000FF,&H005D657C,&H8D253953,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Voleur,UVN Van,80,&H00FFFFFF,&H000000FF,&H003C0618,&H8DFF002D,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Berry,UVN Van,80,&H00FFFFFF,&H000000FF,&H00615B94,&H8D6B67A2,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Noichigo,UVN Van,80,&H00FFFFFF,&H000000FF,&H00615B94,&H8D6B67A2,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Mashirou,UVN Van,80,&H00FFFFFF,&H000000FF,&H00102D38,&H8D00CCFF,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Grandpa,UVN Van,80,&H00FFFFFF,&H000000FF,&H638A777D,&H8D503154,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Mère,UVN Van,80,&H00FFFFFF,&H000000FF,&H0024193E,&H80B7A3F1,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Serveuse,UVN Van,80,&H00FFFFFF,&H000000FF,&H00480D50,&H8DF976FF,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Professeur,UVN Van,80,&H00FFFFFF,&H000000FF,&H0024193E,&H80B7A3F1,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Ako,UVN Van,80,&H00FFFFFF,&H000000FF,&H0020335B,&H8D3D5F94,-1,0,0,0,100,100,0,0,1,4,1,2,10,10,32,1
Style: Sub1,SVN-Bali Script,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,2,3,10,30,20,1
Style: Sub2,SVN-Bali Script,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,2,3,10,60,20,1
Style: Credit,iCiel Pony,60,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.5,2,2,10,10,40,1
Style: Signs,Anton,80,&H001C1C1D,&H000000FF,&H00595658,&H00FFFFFF,0,0,0,0,100,100,0,0,1,0,1.5,5,0,0,0,1
Style: Sub3,SVN-Androgyne,80,&H00FFFFFF,&H002400FF,&H00000000,&H00000000,-1,0,0,0,100,100,0.5,0,1,0,0,8,10,10,25,1
Style: Sub4,SVN-Androgyne,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,25,1


[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:10.37,0:12:31.22,AVS_Logo,,0,0,0,,{\\fad(500,500)\\c&HFFFFFF&\\3c&H0000FF&\\}Anime{\\c&H0000FF&\\3c&HFFFFFF&}Vietsub{\\c&HFFFFFF&\\3c&H0000FF&}
Dialogue: 0,0:12:50.36,2:22:22.22,AVS_Logo,,0,0,0,,{\\fad(500,500)\\c&HFFFFFF&\\3c&H0000FF&\\}Anime{\\c&H0000FF&\\3c&HFFFFFF&}Vietsub{\\c&HFFFFFF&\\3c&H0000FF&}
Dialogue: 0,0:00:00.00,0:10:00.00,AVS_Notify_3,,0,0,0,,{\\fad(500,500)\\pos(960,1034)}Anime được dịch bởi AnimeVietsub.
Dialogue: 0,0:10:01.00,0:15:01.00,AVS_Notify_3,,0,0,0,,{\\fad(500,500)\\pos(960,1034)}Anime Vietsub được cập nhật nhanh nhất, duy nhất tại AnimeVietsub
Dialogue: 0,0:15:01.00,0:25:01.00,AVS_Notify_3,,0,0,0,,{\\fad(500,500)\\pos(960,1034)}Xem anime tại bit.ly/animevietsubtv là ủng hộ nhóm dịch.
Dialogue: 0,0:12:31.22,0:12:40.05,AVS_Hot,,0,0,0,,{\\fad(500,500)\\3c&HFF0400&\\be3\\move(2780,10,-850,10,7,8500)}Lưu lại địa chỉ {\\3c&H0000FF&}bit.ly/animevietsubtv {\\3c&HFF0400&}để truy cập website nhanh nhất khi bị chặn!
Dialogue: 0,0:12:35.65,0:12:45.50,AVS_Hot,,0,0,0,,{\\fad(500,500)\\3c&HFF0400&\\be3\\move(2780,10,-850,10,7,8500)}Lưu lại địa chỉ {\\3c&H0000FF&}bit.ly/animevietsubtv {\\3c&HFF0400&}để truy cập website nhanh nhất khi bị chặn!
Dialogue: 0,0:00:00.00,0:00:09.36,AVS_Hot,,0,0,0,,{\\fad(500,500)\\3c&HFF0400&}Nếu không thể truy cập {\\c&HFFFFFF&\\3c&H0000FF&\\}Anime{\\c&H0000FF&\\3c&HFFFFFF&}Vietsub{\\c&HFFFFFF&\\3c&H0000FF&} {\\c&HFFFFFF&\\3c&HFF0400&}hãy thử lại với {\\c&HFFFFFF&\\3c&H0000FF&\\}bit.ly/{\\c&H0000FF&\\3c&HFFFFFF&}animevietsubtv{\\c&HFFFFFF&\\3c&H0000FF&\\be3\\move(2780,10,-850,10,7,8500)}
Dialogue: 0,0:00:04.00,0:00:12.75,AVS_Hot,,0,0,0,,{\\fad(500,500)\\3c&HFF0400&}Nếu không thể truy cập {\\c&HFFFFFF&\\3c&H0000FF&\\}Anime{\\c&H0000FF&\\3c&HFFFFFF&}Vietsub{\\c&HFFFFFF&\\3c&H0000FF&} {\\c&HFFFFFF&\\3c&HFF0400&}hãy thử lại với {\\c&HFFFFFF&\\3c&H0000FF&\\}bit.ly/{\\c&H0000FF&\\3c&HFFFFFF&}animevietsubtv{\\c&HFFFFFF&\\3c&H0000FF&\\be3\\move(2780,10,-850,10,7,8500)}
"""

def load_anime_list():
    try:
        with open('anime_list.txt', 'r', encoding='utf-8') as f:
            return [line.strip() for line in f.readlines() if line.strip()]
    except FileNotFoundError:
        return []

def save_anime_list(anime_names):
    with open('anime_list.txt', 'w', encoding='utf-8') as f:
        f.write('\n'.join(anime_names))

def get_file_content(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.readlines()
    return content

def write_content_to_file(content, output_dir):
    with open(output_dir, 'w', encoding='utf-8') as file:
        file.writelines(content)
    return output_dir

def create_if_not_exist(anime_name, ep):
    if not os.path.exists(anime_name):
        os.makedirs(anime_name)
    
    new_file_name = f"{anime_name}_Ep{ep}.ass"
    new_file_path = os.path.join(anime_name, new_file_name)
    
    if os.path.exists(new_file_path):
        today = datetime.now()
        folder_suffix = f"{today.day}.{today.month}"
        base, ext = os.path.splitext(new_file_name)
        new_file_name = f"{base}_{folder_suffix}{ext}"
        new_file_path = os.path.join(anime_name, new_file_name)
    return new_file_path

def add_prefix_to_dialogue(content, prefix_str):
    start_index = next((index for index, line in enumerate(content) if "[Events]" in line), 0) + 1
    try:
        for index, line in enumerate(content):
            if index < start_index: continue
            line = content[index]
            content[index] = add_prefix_to_line(line, prefix_str)
    except Exception as e:
        print(f"Error processing line: {line}. Error: {e}")
    finally:  
        return content

def add_prefix_to_line(line, prefix):
    clean_prefix = prefix[1:-1]   
    if not (Text := re.search(r"(^Dialogue: (?:[^,]*,){9})(.*)", line)):
        return line
    base_Text = Text.group(1)
    Text_Content = Text.group(2)    
    if position_style_match := re.search(r"^\{\\pos\(\d+.\d+,\d+.\d+\)\}\{.{,5}\}", Text_Content):
        position_style = position_style_match.group(0)
        replaced_style = position_style.replace(r"}{", clean_prefix)
        Text_Content = Text_Content.replace(position_style, replaced_style)
    else:
        Text_Content = "{" + clean_prefix + "}" + Text_Content        
    return base_Text + Text_Content + "\n"

def override_headers(content, anime_name, ep):
    index = -1
    for i, line in enumerate(content):
        if line.strip().startswith("Format:"):
            index = i
            break
    if index == -1:
         for i, line in enumerate(content):
            if line.strip().startswith("[Events]"):
                index = i + 1 
                break
    anim_name_rep = AVS_ANIME_NAME_TEMPLATE.replace("(Tên Anime - Tập)", f"{anime_name} - Tập {ep}")
    new_header_list = AVS_CONTENT_TEMPLATE.splitlines(True) 
    if new_header_list and not new_header_list[-1].endswith('\n'):
        new_header_list[-1] += '\n'
    new_header_list.append(anim_name_rep + "\n")
    if index != -1:
        old_content_tail = []
        if index < len(content) and content[index].strip().startswith("Format:"):
             old_content_tail = content[index+1:]
        else:
             old_content_tail = content[index:]            
        return new_header_list + old_content_tail
    else:
        return new_header_list + content

def refined_replace_text(content):
    start_index = next((index for index, line in enumerate(content) if "[Events]" in line), -1) + 1
    try:
        for index, line in enumerate(content):
            if index < start_index: continue
            line = content[index]
            content[index] = replace_style_to_line(line)
    except Exception as e:
        print(f"Error processing line: {line}. Error: {e}")
    finally:  
        return content

def replace_style_to_line(line):
    line = line.replace('\ufeff', '')
    parts = line.split(",", 9)
    if len(parts) < 10: return line   
    header_part = parts[0]
    if ":" in header_part:
        format_type = header_part.split(":")[0].strip()
    else:
        return line      
    if format_type != "Dialogue": return line   
    current_name = parts[4]
    current_style = NON_IMPORTANT_ACTOR_STYLE    
    if current_name in EXCEPTION_CASE:
        current_style = EXCEPTION_CASE[current_name]
    else:
        is_non_dialog = False
        for actor in NON_DIALOG_ACTORS:
            if actor == current_name:
                current_style = NON_DIALOG_STYLE
                is_non_dialog = True
                break
            elif actor in current_name:
                current_name = actor
                current_style = NON_DIALOG_STYLE
                is_non_dialog = True
                break       
        if not is_non_dialog:
            for actor in IMPORTANT_ACTORS:
                if actor == current_name:
                    current_name = actor
                    current_style = actor
                    break
                elif actor in current_name:
                    current_name = actor
                    current_style = NON_DIALOG_STYLE 
                    break
    parts[3] = current_style
    parts[4] = current_name   
    return ",".join(parts)
    
class CustomCompleter(QCompleter):
    def splitPath(self, path):
        return [path]

class AnimeNameField(QLineEdit):
    def __init__(self, anime_list_data, parent=None):
        super().__init__(parent)
        self.anime_list = anime_list_data
        self.model = QStringListModel(self.anime_list)
        
        self.proxy_model = QSortFilterProxyModel(self)
        self.proxy_model.setSourceModel(self.model)
        self.proxy_model.setFilterCaseSensitivity(Qt.CaseInsensitive)

        self.completer = CustomCompleter(self)
        self.completer.setModel(self.proxy_model)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.completer.setFilterMode(Qt.MatchContains)
        self.setCompleter(self.completer)       
        self.textChanged.connect(self.updateCompleter)
        
    def updateCompleter(self, text):
        self.proxy_model.setFilterFixedString(text)

    def _title_case_anime_name(self, name):
        words = name.strip().split()
        if not words: return ""
        special_cases = {'ss', 'SS', 'no', 'to', 'wa', 'wo', 'ga', 'de', 'ni'}
        for i in range(len(words)):
            if words[i].lower() == 'ss' and i < len(words) - 1 and words[i + 1].isdigit():
                words[i] = 'SS'
            elif words[i].lower() in special_cases and i > 0:
                words[i] = words[i].lower()
            else:
                words[i] = words[i].capitalize()
        return ' '.join(words)

    def addNewAnime(self, anime_name):
        if not anime_name: return False
        formatted_name = self._title_case_anime_name(anime_name)
        if formatted_name not in self.anime_list:
            self.anime_list.append(formatted_name)
            self.anime_list.sort()
            self.model.setStringList(self.anime_list)
            save_anime_list(self.anime_list)
            return True
        return False

class SubtitleApp(QWidget):
    def __init__(self):
        super().__init__()       
        self.anime_list_data = load_anime_list()
        if not self.anime_list_data:
            QMessageBox.warning(self, "Warning", "Could not load anime list or file is empty.")
        self.setWindowTitle("Subtitle Processor")
        self.setGeometry(400, 400, 400, 250) 
        layout = QVBoxLayout()
        config_label = QLabel("Configuration Options:", self)
        layout.addWidget(config_label)
        self.prefix_checkbox = QCheckBox("Add Prefix", self)
        self.prefix_checkbox.setChecked(False)         
        self.logo_checkbox = QCheckBox("Add Logo", self)
        self.logo_checkbox.setChecked(True)  
        
        self.actor_checkbox = QCheckBox("Change Actor", self)
        self.actor_checkbox.setChecked(False)  

        layout.addWidget(self.prefix_checkbox)
        layout.addWidget(self.logo_checkbox)
        layout.addWidget(self.actor_checkbox)

        self.label = QLabel("Enter the file name or browse for the file:", self)
        self.line_edit = QLineEdit(self)
        self.browse_button = QPushButton("Browse", self)
        self.process_button = QPushButton("Process", self)
        self.status_label = QLabel("", self)

        self.animeNameField = AnimeNameField(self.anime_list_data, self)
        layout.addWidget(self.animeNameField)

        self.add_anime_button = QPushButton("Add Current Anime to List", self)
        self.add_anime_button.clicked.connect(self.add_new_anime)
        layout.addWidget(self.add_anime_button)

        self.episodeNumberDropdown = QComboBox(self)
        self.episodeNumberDropdown.addItems([str(i) for i in range(1, 13)])
        layout.addWidget(self.episodeNumberDropdown)

        self.longAnimeCheckbox = QCheckBox("More Ep", self)
        self.longAnimeCheckbox.stateChanged.connect(self.updateEpisodeDropdown)
        layout.addWidget(self.longAnimeCheckbox)
        
        self.browse_button.clicked.connect(self.browse_file)
        self.process_button.clicked.connect(self.process_file)

        layout.addWidget(self.label)
        layout.addWidget(self.line_edit)
        layout.addWidget(self.browse_button)
        layout.addWidget(self.process_button)
        layout.addWidget(self.status_label)

        self.setLayout(layout)
        
    def browse_file(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(self, "Open ASS File", "", "ASS Files (*.ass);;All Files (*)", options=options)
        if file_name:
            self.line_edit.setText(file_name)

    def updateEpisodeDropdown(self, state):
        if state == Qt.Checked:
            self.episodeNumberDropdown.clear()
            self.episodeNumberDropdown.addItems([f"{i:02d}" for i in range(13, 27)])
        else:
            self.episodeNumberDropdown.clear()
            self.episodeNumberDropdown.addItems([f"{i:02d}" for i in range(1, 13)])

    def add_new_anime(self):
        current_anime = self.animeNameField.text().strip()
        if current_anime:
            if self.animeNameField.addNewAnime(current_anime):
                QMessageBox.information(self, "Success", f"Added '{current_anime}' to anime list!")
            else:
                QMessageBox.information(self, "Info", "Anime already in list or invalid name!")

    def process_file(self):
        file_name = self.line_edit.text()
        if not file_name:
            self.status_label.setText("Please provide a file name or browse for a file.")
            return
        is_add_prefix = self.prefix_checkbox.isChecked()
        is_add_logo = self.logo_checkbox.isChecked()
        is_change_actor = self.actor_checkbox.isChecked()        
        anime_name_input = self.animeNameField.text()
        ep_input = self.episodeNumberDropdown.currentText()

        try:
            out_file = create_if_not_exist(anime_name_input, ep_input)
            content = get_file_content(file_name)
            if is_add_prefix:
                content = add_prefix_to_dialogue(content, STYLE_PREFIX)           
            if is_change_actor:
                content = refined_replace_text(content)           
            if is_add_logo:
                content = override_headers(content, anime_name_input, ep_input)       
            write_content_to_file(content, out_file)           
            self.status_label.setText(f"Processed successfully! Output at: {out_file}")
        except Exception as e:
            print(traceback.format_exc())
            self.status_label.setText(f"Error: {str(e)}")

def start_application():
    app = QApplication(sys.argv)
    QApplication.setStyle('Fusion')
    window = QMainWindow()
    window = SubtitleApp()
    window.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    start_application()